name: Gradle Build and test

on: [ push,pull_request ]

env:
  GPR_USER: ${{ secrets.GITHUB_USERNAME }}
  GPR_KEY: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    uses: Nachoferra1894/ingsis-actions/.github/workflows/gradle-test.yml@main
