name: Gradle Build and test

on: [ push,pull_request ]

env:
  USERNAME: ${{ secrets.GITHUB_USERNAME }}
  TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    uses: Nachoferra1894/ingsis-actions/.github/workflows/gradle-test.yml@main
